name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push web-app image
      working-directory: ./web-app
      run: |
        docker buildx build --platform linux/amd64 -t giladaslan9/web-app:latest .
        docker push giladaslan9/web-app:latest

    - name: Build and push backend image
      working-directory: ./backend
      run: |
        docker buildx build --platform linux/amd64 -t giladaslan9/backend:latest .
        docker push giladaslan9/backend:latest
